### PR TITLE
Fixes warnings caused by having useused css properties

### PR DESCRIPTION
**Pull request by st23am**
Sass outputs warnings if there are css selectors that have no properties. We don't need these lets remove them.

selfie-1

### CODE REVIEW

**Comment by kclasita** [comment]
Silly designer question here. 

So my work today was moving where these css files are located and what's in them. Since this is only a couple of changes, is it easier to merge my changes in and just do those changes again? Is there something better?

**Comment by st23am** [comment]
@kclasita you probably want to apply this commit first but, It shouldn't be a problem either way. If it is let me know and I'll fix it up.

**Comment by kclasita** [comment]
I've already merged my branch in. If you want to merge this in that's fine, or I can do these changes.

**Comment by st23am** [comment]
Updated and rebased on master

**Pull request closed without merging**
